### ISSUE TITLE
Infinite looping when filenames are exhausted

### ISSUE THREAD

**Issue by rjz** [sasaplus1/mktemp#7]
Attempting to create a temporary file or directory from an "exhausted" template (i.e., one where all permutations already exist on disk) can lead to an infinite loop. In the worst case, this scenario can block further synchronous processing; in all cases it needlessly chews through system resources.

Instead of allowing methods to continue running indefinitely, let's indicate failure after a reasonable number of file creation attempts and allow userland code to take additional steps as appropriate.

**Comment by sasaplus1** [comment]
merged by #8
