### ISSUE TITLE
Typings missing in 1.0.0

### ISSUE THREAD

**Issue by charlespwd** [sasaplus1/mktemp#81]
I see the typings on main but not in the published repo.

![image](https://user-images.githubusercontent.com/4990691/235710179-5a075e5f-4005-44cd-9ef9-99843984c0f7.png)

Looks like all we need is a 1.0.1 publish :)

**Comment by sasaplus1** [comment]
Oh

**Comment by sasaplus1** [comment]
fix by ver.1.0.1. Thanks!
